### PR TITLE
Support SameSite cookie parameter

### PR DESCRIPTION
**Pull request by pesekviktor**

### CODE REVIEW

**Comment by maticzav** [comment]
Does the package size increase?

**Comment by pesekviktor** [comment]
I removed ramda and put in a simple object properties test (should be adequate for cookies). Now the size change should be insignificant

**Comment by maticzav** [comment]
@pesekviktor what do we gain with this PR? Is it only the code structure change or also a performance/... increase?

**Comment by pesekviktor** [comment]
The purpose is to support SameSite cookie attribute. I could just add samesite to the list, however this way it should pass all the attributes if there was another missing.  The performance effect should be negligable...

**Comment by AquiburRahmanKhan** [comment]
Hello,

**Comment by AquiburRahmanKhan** [comment]
Hello, will this PR be merged soon ? I think this resolves the samesite cookie warning that we are getting from chrome 80 , right ?

**Comment by AquiburRahmanKhan** [comment]
@maticzav , thanks so much for merging this PR, can you please update the npm package too when you get the time , thanks again :)

**Comment by maticzav** [comment]
Published! 🙂

**Comment by AquiburRahmanKhan** [comment]
Thanks again :D

**Pull request merged**
