### PR TITLE
Fix import

### PR DESCRIPTION
**Pull request by karlhorky**
Add the missing named imports to the frontend example in the readme.

### CODE REVIEW

**Comment by maticzav** [comment]
is this still relevant?

**Comment by karlhorky** [comment]
@maticzav yep! I wasn't sure whether #232 would be accepted, so this was separate. Still needs to be fixed.

**Comment by maticzav** [comment]
Thank you for the PRs

**Comment by karlhorky** [comment]
No worries, thanks for merging!

**Pull request merged**
